/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [Full WBS Code]
      ,[ConstructionCostCode]
      ,[ConstructionCostName]
      ,[WBSAccountingCode]
      ,[WBSAccountingName]
      ,[SubWBSAccountingName]
      ,[WBSProjectCode]
      ,[WBSProjectName]
      ,[AssetClass Name - TI]
      ,[AssetClass]
      ,[WBSCodeStatus]
      ,[SalesTax]
      ,[WBSCodeType]
      ,[GCSOV]
      ,[ProphixAssetClass - TI]
      ,[SubmissionAssetClass]
  FROM [dbo].[vw_Build_FinWBScodes]