---
output:
  word_document: default
  html_document: default
---

### Lab 3 - Normal Distribution
#### Matt Graham

Data gathering and prep
```{r}
download.file("http://www.openintro.org/stat/data/bdims.RData", destfile = "bdims.RData")
load("bdims.RData")
head(bdims)
```

Creating subsets between sex-assigned males and females
```{r}
mdims <- subset(bdims, sex == 1)
fdims <- subset(bdims, sex == 0)
```

### Exercise 1
#### a - bii.di

This matches with Plot B
a) pelvic diameter
```{r}
fbiidimean <- mean(fdims$bii.di)
fbiidisd   <- sd(fdims$bii.di)

hist(fdims$bii.di, probability = TRUE, ylim = c(0, 0.2))
x <- 15:35
y <- dnorm(x = x, mean = fbiidimean, sd = fbiidisd)
lines(x = x, y = y, col = "blue")

summary(fdims$bii.di)
c(fbiidimean, fbiidisd)

qqnorm(fdims$bii.di)
qqline(fdims$bii.di)
```


#### b - elb.di

Matches Plot C

b) elbow diameter
```{r}
felbdimean <- mean(fdims$elb.di)
felbdisd   <- sd(fdims$elb.di)

hist(fdims$elb.di, probability = TRUE, ylim = c(0, 0.5))
x <- 5:20
y <- dnorm(x = x, mean = felbdimean, sd = felbdisd)
lines(x = x, y = y, col = "blue")

summary(fdims$elb.di)
c(felbdimean, felbdisd)

qqnorm(fdims$elb.di)
qqline(fdims$elb.di)
```


#### c) age

Matches Plot D

```{r}
fagemean <- mean(fdims$age)
fagesd   <- sd(fdims$age)

hist(fdims$age, probability = TRUE, ylim = c(0, 0.07))
x <- 15:70
y <- dnorm(x = x, mean = fagemean, sd = fagesd)
lines(x = x, y = y, col = "blue")

summary(fdims$age)
c(fagemean, fagesd)

qqnorm(fdims$age)
qqline(fdims$age)
```


#### d) chest depth

Matches plot A

```{r}
fchedemean <- mean(fdims$che.de)
fchedesd   <- sd(fdims$che.de)

hist(fdims$che.de, probability = TRUE, ylim = c(0, 0.3))
x <- 10:30
y <- dnorm(x = x, mean = fchedemean, sd = fchedesd)
lines(x = x, y = y, col = "blue")

summary(fdims$che.de)
c(fchedemean, fchedesd)

qqnorm(fdims$che.de)
qqline(fdims$che.de)
```


Discussion
```{r}
library(fitdistrplus)
# Calculate the IQR
iqr <- IQR(fdims$che.de)
# Identify outliers
# outliers <- boxplot(fdims$che.de)$fliers
# Remove the outliers
fdims <- fdims[-outliers]
# Fit a normal distribution to the che.de column of the fdims data set
fit <- fitdistr(fdims$che.de, "norm")
# Print the summary of the fitted distribution
summary(fit)
```
