# -*- coding: utf-8 -*-
"""Copy of ex_2-1_mortality.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16SIE534ewL6i4WtqYQz-n-o1KomQyVsN

# Chapter 2: Mortality
"""

import pandas as pd
import openpyxl

"""## Get the data"""

mortality_url = "https://data.cdc.gov/api/views/v6ab-adf5/rows.csv?accessType=DOWNLOAD"
mortality_data = pd.read_csv(mortality_url)

"""### Save and restore the DataFrame"""

mortality_data.to_pickle('mortality_data.pkl')

mortality_data = pd.read_pickle('mortality_data.pkl')

"""## Examine and clean the data

### Display the data
"""

mortality_data

mortality_data.head()

mortality_data.tail(3)

display(mortality_data)

with pd.option_context(
    'display.max_rows', 5,
    'display.max_columns', None):
    display(mortality_data)

"""### Display the DataFrame attributes"""

mortality_data.values

print("Index:  ", mortality_data.index)
print("Columns:", mortality_data.columns)
print("Size:   ", mortality_data.size)
print("Shape:  ", mortality_data.shape)

"""### Use the columns attribute to change the column names"""

mortality_data.columns = mortality_data.columns.str.replace(" ", "")

print(mortality_data.columns)

mortality_data.head()

"""### Use the info(), nunique(), and describe() methods"""

mortality_data.info()

mortality_data.info(memory_usage='deep')

mortality_data.nunique()

mortality_data.describe()

mortality_data.describe().T

"""### Save and restore the cleaned DataFrame"""

mortality_data.to_pickle('mortality_cleaned.pkl')

mortality_data = pd.read_pickle('mortality_cleaned.pkl')
mortality_data.head()

"""## Access the data

### How to access columns
"""

mortality_data.DeathRate.head(2)

type(mortality_data.DeathRate)

mortality_data['DeathRate'].head(2)

type(mortality_data['DeathRate'])

mortality_data[['Year','DeathRate']].head(2)

type(mortality_data[['Year','DeathRate']])

"""### How to access rows"""

mortality_data.query('Year==1900')

mortality_data.query('Year == 2000 and AgeGroup != "1-4 Years"')

mortality_data.query('Year == 1900 or Year == 2000').head()

# use backticks if a column name contains spaces
# mortality_data.query('Year == 2000 and `Age Group` != "1-4 Years"')

"""### How to access a subset of rows and columns"""

mortality_data.query('Year == 1900').DeathRate.head()

mortality_data.query('Year == 1900')['DeathRate'].head()

mortality_data.query('Year == 1900')[['DeathRate']].head()

mortality_data.query('Year == 1900')[['AgeGroup','DeathRate']].head()

"""### How to access rows with the loc[] accessor"""

mortality_data.loc[[0,5,10]]

mortality_data.loc[4:6]

mortality_data.loc[0:20:5]

mortality_data.loc[mortality_data.Year == 1917]

"""### How to access columns with the loc[] accessor"""

mortality_data.loc[:, ['Year', 'AgeGroup']]

"""### How to access a subset of rows and columns with the loc[] accessor"""

mortality_data.loc[[0,5,10],['AgeGroup','DeathRate']]

mortality_data.loc[4:6,'AgeGroup':'DeathRate']

"""### How to access rows with the iloc[] accessor"""

mortality_data.iloc[[0,5,10]]

mortality_data.iloc[4:6]

mortality_data.iloc[0:20:5]

"""### How to access a subset of rows and columns with the iloc[] accessor"""

mortality_data.iloc[[0,5,10],[1,2]]

mortality_data.iloc[4:7,1:3]

mortality_data.iloc[-10:]

"""## Prepare the data

### Sort the data
"""

mortality_data.sort_values('DeathRate', ascending=False).head(3)

mortality_data.sort_values(['Year','DeathRate']).head(3)

mortality_data.sort_values(['Year','DeathRate'],
                           ascending=[True,False]).head()

mortality_data.sort_values(['DeathRate','Year'],
                           ascending=[False,True]).head()

"""### Apply statistical methods"""

mortality_data.DeathRate.mean()

mortality_data[['AgeGroup','DeathRate']].max()

mortality_data.count()

mortality_data.quantile([.1,.9])

mortality_data['DeathRate'].cumsum()

"""### Use Python for column arithmetic"""

mortality_data['MeanCentered'] = \
    mortality_data.DeathRate - mortality_data.DeathRate.mean()

mortality_data

mortality_data['DeathRate'] = mortality_data.DeathRate / 100000

mortality_data.head()

"""### Modify the string data in a column"""

mortality_data.AgeGroup.replace(
    {'1-4 Years':'01-04 Years','5-9 Years':'05-09 Years'},
    inplace = True)

mortality_data.AgeGroup.replace(
    to_replace = ['1-4 Years','5-9 Years'],
    value = ['01-04 Years','05-09 Years'],
    inplace = True)

# mortality_data['AgeGroup'] = mortality_data.AgeGroup.str.replace('1-4 Years','01-04 Years')
# mortality_data['AgeGroup'] = mortality_data.AgeGroup.str.replace('5-9 Years','05-09 Years')

mortality_data

"""### Save and restore the prepared DataFrame"""

mortality_data.to_pickle('mortality_prepped.pkl')

mortality_data = pd.read_pickle('mortality_prepped.pkl')
mortality_data.head()

"""## Shape the data

### Set and use an index
"""

mortality_data.head(2)

mortality_data = mortality_data.set_index('Year')
mortality_data.head(2)

mortality_data.reset_index(inplace=True)

mortality_data = mortality_data.set_index(
    ['Year','AgeGroup'],verify_integrity=True)
mortality_data.head(2)

mortality_data.reset_index(inplace=True)

mortality_data.head(2)

"""### Pivot the data"""

mortality_wide = mortality_data.pivot(
    index="Year",columns="AgeGroup")
mortality_wide.head(3)

mortality_wide = mortality_data.pivot(
    index="Year",columns="AgeGroup",values="DeathRate")
mortality_wide.head(3)

"""### Melt the data"""

mortality_wide.to_excel('mortality_wide.xlsx')

mortality_wide = pd.read_excel('mortality_wide.xlsx')
mortality_wide.head(4)

mortality_long = mortality_wide.melt(
    id_vars = 'Year',
    value_vars=['01-04 Years','05-09 Years'],
    var_name ='AgeGroup',
    value_name='DeathRate')
mortality_long.head(4)
with pd.option_context('display.max_rows', 4):
    display(mortality_long)

"""### Save and restore the wide DataFrame"""

mortality_wide.to_pickle('mortality_wide.pkl')

mortality_wide = pd.read_pickle('mortality_wide.pkl')
mortality_wide.head()

"""## Analyze the data

### Group the data
"""

mortality_data.head()

mortality_data.groupby('AgeGroup').mean()

mortality_data.groupby('Year').median().head(4)

mortality_data.groupby(['Year','AgeGroup']).count().head()

mortality_data.groupby('AgeGroup')['DeathRate'].describe()

"""### Aggregate the data"""

mortality_data.groupby('AgeGroup').agg(['mean','median'])

mortality_data.groupby('AgeGroup')['DeathRate'] \
    .agg(['mean','median','std','nunique'])

mortality_data.groupby('Year')['DeathRate'] \
    .agg(['mean','median','std','min','max','var','nunique'])

"""## Visualize the data"""

mortality_data.pivot(index='Year',columns='AgeGroup')['DeathRate'].plot()

mortality_data.groupby('AgeGroup')['DeathRate'] \
    .agg(['mean','median','std']).plot.barh()

